# Generated by Django 2.1.5 on 2019-03-12 15:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [('bookrank', '0006_more_bookrank_algos'), ('candidates', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='CandidatePrediction',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('score', models.DecimalField(decimal_places=9, max_digits=12)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'candidate',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate'
                    ),
                ),
                (
                    'mi',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='bookrank.BRModelInstance'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
