# Generated by Django 2.2.16 on 2020-10-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('candidates', '0003_predictions_unique_for_mi_candidate')]

    operations = [migrations.DeleteModel(name='CandidatePrediction')]
