# Generated by Django 2.2.23 on 2021-06-29 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('candidates', '0004_delete_candidateprediction')]

    operations = [migrations.DeleteModel(name='Candidate'), migrations.DeleteModel(name='Source')]
