# Generated by Django 2.2.23 on 2021-07-27 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookrank', '0023_work_isbn'),
        ('candidates', '0007_related_name_for_candidate_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCategoryCandidate',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'candidate',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='candidates.Candidate'
                    ),
                ),
                (
                    'topic',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='bookrank.SubjectCategory'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='subjects',
            field=models.ManyToManyField(
                blank=True,
                related_name='candidates',
                through='candidates.SubjectCategoryCandidate',
                to='bookrank.SubjectCategory',
            ),
        ),
    ]
