# Generated by Django 2.2.18 on 2021-10-11 06:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('candidates', '0009_adds_bookmarks_and_blacklists')]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='static_scores',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict,
                help_text='stores scores accumulated from static scores of related languages, '
                'publishers, etc.',
            ),
        )
    ]
