# Generated by Django 3.2.8 on 2021-11-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('candidates', '0011_candidateworklink')]

    operations = [
        migrations.AlterField(
            model_name='candidate', name='extra_data', field=models.JSONField(default=dict)
        ),
        migrations.AlterField(
            model_name='candidate',
            name='static_scores',
            field=models.JSONField(
                default=dict,
                help_text='stores scores accumulated from static scores of related languages, publishers, etc.',
            ),
        ),
    ]
