# Generated by Django 3.2.8 on 2021-12-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('candidates', '0012_json_field_change')]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='isbn',
            field=models.CharField(db_index=True, max_length=20),
        )
    ]
