# Generated by Django 3.2.8 on 2021-12-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('candidates', '0013_candidate_isbn_index')]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True),
        )
    ]
