# Generated by Django 3.2.8 on 2022-01-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('candidates', '0014_candidate_publication_year')]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='product_format',
            field=models.CharField(blank=True, max_length=8),
        )
    ]
