# Generated by Django 3.2.8 on 2022-02-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('candidates', '0016_candidatessettings')]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='normalized_scores',
            field=models.JSONField(
                default=dict,
                help_text='stores scores accumulated from normalized scores of related languages, publishers, etc.',
            ),
        )
    ]
