# Generated by Django 2.1.3 on 2018-11-12 16:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='AlephEntry',
            fields=[
                ('uid', models.SlugField(max_length=16, primary_key=True, serialize=False)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        )
    ]
