default_stages: [push, commit]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        exclude: '^.*\.(tsv|json|svg|csv|xml)'
      - id: end-of-file-fixer
        exclude: '^.*\.(tsv|json|svg|csv|xml)'
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=2000']

  - repo: local
    hooks:
      - id: black
        name: Black formatter
        entry: poetry run black --check
        language: system
        types: [python]
      - id: pytestnow
        name: Check that no tests marked with 'now' exist
        entry: "@pytest.mark.now"
        language: pygrep
        types: [python]

#  - repo: https://github.com/prettier/prettier
#    rev: "2.1.2" # Use the sha or tag you want to point at
#    hooks:
#      - id: prettier
#        files: ^design/
