# Generated by Django 2.2.9 on 2020-01-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='SingletonValue',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('key', models.SlugField(unique=True)),
                ('integer', models.IntegerField(null=True)),
                ('float', models.FloatField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('text', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        )
    ]
