# Generated by Django 2.2.16 on 2020-11-12 10:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                (
                    'ssid',
                    models.CharField(db_index=True, help_text='Source specific ID', max_length=64),
                ),
                ('isbn13', models.CharField(blank=True, db_index=True, max_length=13)),
                ('doi', models.CharField(blank=True, max_length=256)),
                (
                    'other_ids',
                    django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
                ),
                ('title', models.TextField(blank=True)),
                (
                    'extracted_data',
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Any data of interest extracted from raw data',
                    ),
                ),
                (
                    'timestamp',
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text='Timestamp extracted from the source data',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=32, unique=True)),
                (
                    'data_format',
                    models.CharField(
                        choices=[
                            ('marc21', 'MARC21'),
                            ('onix2.1', 'ONIX2.1'),
                            ('onix3.0', 'ONIX3.0'),
                        ],
                        max_length=12,
                    ),
                ),
                ('description', models.TextField(blank=True)),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='RawDataRecord',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('data', models.BinaryField(null=True)),
                ('fmt', models.CharField(choices=[('XML', 'XML'), ('JSON', 'JSON')], max_length=4)),
                (
                    'record',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='raw_data',
                        to='source_data.DataRecord',
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.AddField(
            model_name='datarecord',
            name='source',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='source_data.DataSource'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='datarecord', unique_together={('ssid', 'source', 'timestamp')}
        ),
    ]
