# Generated by Django 2.1.5 on 2019-01-10 13:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('bookrank', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='brmodelinstance',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        )
    ]
