# Generated by Django 2.1.5 on 2019-01-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('bookrank', '0002_brmodelinstance_params')]

    operations = [migrations.AlterModelOptions(name='workset', options={'ordering': ('-created',)})]
