# Generated by Django 2.1.5 on 2019-01-18 12:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('bookrank', '0003_workset_meta_change')]

    operations = [
        migrations.CreateModel(
            name='WorkScoreTopicScoreLink',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'wt_influence',
                    models.DecimalField(
                        decimal_places=6, help_text='Work-Topic influence', max_digits=15
                    ),
                ),
                (
                    'tw_influence',
                    models.DecimalField(
                        decimal_places=6, help_text='Topic-Work influence', max_digits=15
                    ),
                ),
                (
                    'params',
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=dict,
                        help_text='Storage for additional parameters of influence computation',
                    ),
                ),
                (
                    'topicscore',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='bookrank.TopicScore'
                    ),
                ),
                (
                    'workscore',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='bookrank.WorkScore'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='workscore',
            name='related_topicscores',
            field=models.ManyToManyField(
                related_name='related_workscores',
                through='bookrank.WorkScoreTopicScoreLink',
                to='bookrank.TopicScore',
            ),
        ),
    ]
