# Generated by Django 2.1.5 on 2019-01-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('bookrank', '0004_exlicit_workscore_topicscore_link')]

    operations = [
        migrations.AddField(
            model_name='brmodel',
            name='algorithm',
            field=models.CharField(
                choices=[('fair', 'Fair'), ('charitable', 'Charitable')],
                default='charitable',
                max_length=32,
            ),
        )
    ]
