# Generated by Django 2.2.6 on 2019-10-09 11:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


def typ_to_int_typ(apps, schema_editor):
    topic_model = apps.get_model('bookrank', 'Topic')
    topic_model.objects.filter(typ='AU').update(int_typ=1)
    topic_model.objects.filter(typ='KW').update(int_typ=2)
    topic_model.objects.filter(typ='CAT').update(int_typ=100)
    topic_model.objects.filter(typ='GEN').update(int_typ=255)
    topic_subtype_model = apps.get_model('bookrank', 'TopicSubType')
    topic_subtype_model.objects.filter(topic_type='AU').update(int_topic_type=1)
    topic_subtype_model.objects.filter(topic_type='KW').update(int_topic_type=2)
    topic_subtype_model.objects.filter(topic_type='CAT').update(int_topic_type=100)
    topic_subtype_model.objects.filter(topic_type='GEN').update(int_topic_type=255)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [('bookrank', '0006_more_bookrank_algos')]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='int_typ',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Author'),
                    (2, 'Keyword'),
                    (3, 'Language'),
                    (4, 'Publisher'),
                    (100, 'Category'),
                    (255, 'Generated'),
                ],
                default=0,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicsubtype',
            name='int_topic_type',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Author'),
                    (2, 'Keyword'),
                    (3, 'Language'),
                    (4, 'Publisher'),
                    (100, 'Category'),
                    (255, 'Generated'),
                ],
                default=0,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brmodel',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default={
                    'forward_topic_weighing': True,
                    'topic_type_to_weight_coef': {1: 1.0, 2: 1.0, 100: 1.0, 255: 1.0},
                },
            ),
        ),
        migrations.RunPython(typ_to_int_typ, noop),
    ]
