# Generated by Django 2.2.6 on 2019-10-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('bookrank', '0007_topic_int_type')]

    operations = [
        migrations.RemoveField(model_name='topic', name='typ'),
        migrations.RemoveField(model_name='topicsubtype', name='topic_type'),
        migrations.RenameField(model_name='topic', old_name='int_typ', new_name='typ'),
        migrations.RenameField(
            model_name='topicsubtype', old_name='int_topic_type', new_name='topic_type'
        ),
    ]
