# Generated by Django 2.2.6 on 2019-10-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('bookrank', '0008_remove_char_topic_type')]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='typ',
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, 'Author'),
                    (2, 'Keyword'),
                    (3, 'Language'),
                    (4, 'Publisher'),
                    (100, 'Category'),
                    (255, 'Generated'),
                ],
                db_index=True,
            ),
        )
    ]
