# Generated by Django 2.2.6 on 2019-10-14 13:45

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Prefetch

from ..models import TYP_LANG


def extract_lang(apps, schema_editor):
    topic_model = apps.get_model('bookrank', 'Topic')
    work_model = apps.get_model('bookrank', 'Work')
    topic_queryset = topic_model.objects.filter(typ=TYP_LANG).only('pk')
    for work in work_model.objects.all().prefetch_related(
        Prefetch('topics', queryset=topic_queryset, to_attr='lang_topics')
    ):
        langs = work.lang_topics
        if langs:
            work.lang_id = langs[0].pk
            work.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [('bookrank', '0009_topic_typ_index')]

    operations = [
        migrations.AddField(
            model_name='work',
            name='lang',
            field=models.ForeignKey(
                limit_choices_to={'typ': 3},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='lang_works',
                to='bookrank.Topic',
            ),
        ),
        migrations.RunPython(extract_lang, noop),
    ]
