# Generated by Django 2.2.6 on 2019-10-17 08:21

import django.utils.timezone
from django.db import migrations, models

# following are extracted from models to be preserved in history
TYP_AUTHOR = 1
TYP_KEYWORD = 2
TYP_LANG = 3
TYP_PUBLISHER = 4
TYP_CATEGORY = 100
TYP_GENERATED = 255


def extract_explicit_topics(apps, schema_editor):
    language_model = apps.get_model('bookrank', 'Language')
    topic_model = apps.get_model('bookrank', 'Topic')
    for topic in topic_model.objects.filter(typ=TYP_LANG):
        lang = language_model.objects.create(name=topic.name, work_set_id=topic.work_set_id)
        topic.works.all().update(lang=lang)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [('bookrank', '0012_explicit_publisher_author')]

    operations = [
        migrations.RemoveField(model_name='work', name='lang'),
        migrations.CreateModel(
            name='Language',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                (
                    'work_set',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='bookrank.WorkSet'
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.AddField(
            model_name='work',
            name='lang',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='works',
                to='bookrank.Language',
            ),
        ),
        migrations.RunPython(extract_explicit_topics, noop),
    ]
