# Generated by Django 2.2.6 on 2019-10-17 13:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [('bookrank', '0013_explicit_language')]

    operations = [
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                (
                    'parent',
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='children',
                        to='bookrank.SubjectCategory',
                    ),
                ),
                (
                    'work_set',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='bookrank.WorkSet'
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='SubjectCategoryWork',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'subject_category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='bookrank.SubjectCategory'
                    ),
                ),
                (
                    'work',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='bookrank.Work'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='subject_categories',
            field=models.ManyToManyField(
                related_name='works',
                through='bookrank.SubjectCategoryWork',
                to='bookrank.SubjectCategory',
            ),
        ),
    ]
