# Generated by Django 2.2.6 on 2019-10-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('bookrank', '0014_explicit_subjectcategory')]

    operations = [
        migrations.RenameField(model_name='authorwork', old_name='author', new_name='topic'),
        migrations.RenameField(model_name='publisherwork', old_name='publisher', new_name='topic'),
        migrations.RenameField(
            model_name='subjectcategorywork', old_name='subject_category', new_name='topic'
        ),
    ]
