# Generated by Django 2.2.6 on 2019-11-18 15:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [('bookrank', '0015_normalize_connecting_models')]

    operations = [
        migrations.AddField(
            model_name='work',
            name='end_yop',
            field=models.PositiveSmallIntegerField(
                blank=True, help_text='End year of publication', null=True
            ),
        ),
        migrations.AddField(
            model_name='work',
            name='start_yop',
            field=models.PositiveSmallIntegerField(
                blank=True, help_text='Start year of publication', null=True
            ),
        ),
        migrations.AddField(
            model_name='workcategory',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workcategory',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workcategory',
            name='work_set',
            field=models.ForeignKey(
                default=31, on_delete=django.db.models.deletion.CASCADE, to='bookrank.WorkSet'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='works',
                to='bookrank.WorkCategory',
            ),
        ),
        migrations.CreateModel(
            name='OwnerInstitution',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=250)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                (
                    'work_set',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='bookrank.WorkSet'
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.AddField(
            model_name='work',
            name='owner_institution',
            field=models.ForeignKey(
                blank=True,
                help_text='Owner library identification',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='works',
                to='bookrank.OwnerInstitution',
            ),
        ),
    ]
