# Generated by Django 2.2.6 on 2019-11-18 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('bookrank', '0016_more_explicit_topics')]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='works',
                to='bookrank.WorkCategory',
            ),
        ),
        migrations.AlterField(
            model_name='work',
            name='owner_institution',
            field=models.ForeignKey(
                blank=True,
                help_text='Owner library identification',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='works',
                to='bookrank.OwnerInstitution',
            ),
        ),
    ]
