# Generated by Django 2.2.7 on 2019-12-16 13:09

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [('bookrank', '0017_nullable_work_category')]

    operations = [
        TrigramExtension(),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS bookrank_work_work_name_trgm ON bookrank_work "
            "USING GIN (name gin_trgm_ops);",
            "DROP INDEX bookrank_work_work_name_trgm;",
        ),
    ]
