# Generated by Django 2.2.10 on 2020-03-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('bookrank', '0018_trgm_index')]

    operations = [
        migrations.AddField(
            model_name='subjectcategory',
            name='is_controlled_dictionary',
            field=models.BooleanField(
                default=True,
                help_text='When true, the subtree is fixed and should not be extended during export - used for top-level nodes only',
            ),
        )
    ]
