# Generated by Django 2.2.16 on 2020-10-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_delete_candidateprediction'),
        ('bookrank', '0019_subjectcategory_is_controlled_dictionary'),
    ]

    operations = [
        migrations.RemoveField(model_name='brmodelinstance', name='model'),
        migrations.RemoveField(model_name='brmodelinstance', name='topics'),
        migrations.RemoveField(model_name='brmodelinstance', name='work_set'),
        migrations.RemoveField(model_name='brmodelinstance', name='works'),
        migrations.RemoveField(model_name='topicscore', name='mi'),
        migrations.RemoveField(model_name='topicscore', name='topic'),
        migrations.RemoveField(model_name='workscore', name='mi'),
        migrations.RemoveField(model_name='workscore', name='related_topicscores'),
        migrations.RemoveField(model_name='workscore', name='work'),
        migrations.RemoveField(model_name='workscoretopicscorelink', name='topicscore'),
        migrations.RemoveField(model_name='workscoretopicscorelink', name='workscore'),
        migrations.DeleteModel(name='BRModel'),
        migrations.DeleteModel(name='BRModelInstance'),
        migrations.DeleteModel(name='TopicScore'),
        migrations.DeleteModel(name='WorkScore'),
        migrations.DeleteModel(name='WorkScoreTopicScoreLink'),
    ]
