# Generated by Django 2.2.16 on 2020-10-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('bookrank', '0020_delete_brmodel_and_related_models')]

    operations = [
        migrations.AddField(
            model_name='workset', name='last_updated', field=models.DateTimeField(auto_now=True)
        ),
        migrations.AddField(
            model_name='worktopic', name='last_updated', field=models.DateTimeField(auto_now=True)
        ),
    ]
