# Generated by Django 2.2.23 on 2021-06-09 08:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('bookrank', '0022_remove_topic_worktopic_topicsubtype')]

    operations = [
        migrations.AddField(
            model_name='work',
            name='isbn',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=15), default=list, size=None
            ),
        )
    ]
