# Generated by Django 3.2.8 on 2021-11-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('bookrank', '0025_work_acquisition_score')]

    operations = [
        migrations.AddField(
            model_name='author',
            name='absolute_growth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='relative_growth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='score_past_yr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='score_yr_b4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='absolute_growth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='relative_growth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='score_past_yr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='score_yr_b4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerinstitution',
            name='absolute_growth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerinstitution',
            name='relative_growth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerinstitution',
            name='score_past_yr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerinstitution',
            name='score_yr_b4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='absolute_growth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='relative_growth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='score_past_yr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='score_yr_b4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectcategory',
            name='absolute_growth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectcategory',
            name='relative_growth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectcategory',
            name='score_past_yr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subjectcategory',
            name='score_yr_b4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='absolute_growth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='relative_growth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='score_past_yr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work', name='score_yr_b4', field=models.IntegerField(blank=True, null=True)
        ),
        migrations.AddField(
            model_name='workcategory',
            name='absolute_growth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workcategory',
            name='relative_growth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workcategory',
            name='score_past_yr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workcategory',
            name='score_yr_b4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='static_score',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='language',
            name='static_score',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='ownerinstitution',
            name='static_score',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='static_score',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='subjectcategory',
            name='static_score',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='work', name='extra_data', field=models.JSONField(blank=True, default=dict)
        ),
        migrations.AlterField(
            model_name='workcategory',
            name='static_score',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
