# Generated by Django 3.2.8 on 2022-01-31 06:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [('bookrank', '0026_static_growth_fields')]

    operations = [
        migrations.CreateModel(
            name='WorkCopy',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(max_length=10, null=True)),
                ('acquisition_date', models.DateField(null=True)),
                (
                    'work',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='copies',
                        to='bookrank.work',
                    ),
                ),
            ],
            options={'abstract': False},
        )
    ]
