# Generated by Django 3.2.8 on 2022-02-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('bookrank', '0027_workcopy')]

    operations = [
        migrations.AddField(
            model_name='author', name='normalized_score', field=models.JSONField(default=dict)
        ),
        migrations.AddField(
            model_name='language', name='normalized_score', field=models.JSONField(default=dict)
        ),
        migrations.AddField(
            model_name='ownerinstitution',
            name='normalized_score',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='publisher', name='normalized_score', field=models.JSONField(default=dict)
        ),
        migrations.AddField(
            model_name='subjectcategory',
            name='normalized_score',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='workcategory', name='normalized_score', field=models.JSONField(default=dict)
        ),
    ]
