# Generated by Django 3.2.8 on 2022-02-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('bookrank', '0028_et_normalized_score')]

    operations = [
        migrations.AddField(
            model_name='work',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        )
    ]
