# Generated by Django 2.1.5 on 2019-01-21 15:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('target_id', models.CharField(max_length=120)),
                ('score', models.IntegerField(default=1, help_text='Size or number of the hit(s)')),
                (
                    'date',
                    models.DateField(
                        blank=True,
                        help_text='May be empty in cases where date is not known',
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='HitSet',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=120)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HitType',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='hit',
            name='hitset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hits.HitSet'),
        ),
        migrations.AddField(
            model_name='hit',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hits.HitType'),
        ),
    ]
