# Generated by Django 2.2.23 on 2021-06-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('hits', '0001_squashed_0009_delete_topichit')]

    operations = [
        migrations.AlterField(
            model_name='hittype', name='slug', field=models.SlugField(max_length=20)
        ),
        migrations.DeleteModel(name='Hit'),
        migrations.DeleteModel(name='HitSet'),
    ]
