# Generated by Django 2.2.6 on 2019-10-08 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookrank', '0006_more_bookrank_algos'),
        ('hits', '0002_hit_target_id_textfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHit',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('value', models.IntegerField(default=1)),
                (
                    'date',
                    models.DateField(
                        blank=True,
                        help_text='May be empty in cases where date is not known',
                        null=True,
                    ),
                ),
                (
                    'work',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='bookrank.Work'
                    ),
                ),
            ],
        )
    ]
