# Generated by Django 2.2.6 on 2019-10-09 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('hits', '0003_workhit')]

    operations = [
        migrations.AddField(
            model_name='workhit',
            name='typ',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='hits.HitType'
            ),
        )
    ]
