# Generated by Django 2.2.6 on 2019-10-09 14:07

from django.db import migrations, models
from django.db.models import F


def name_to_slug(apps, schema_editor):
    hittype_model = apps.get_model('hits', 'HitType')
    hittype_model.objects.all().update(slug=F('name'))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [('hits', '0005_workhit_created')]

    operations = [
        migrations.AddField(
            model_name='hittype',
            name='slug',
            field=models.SlugField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.RunPython(name_to_slug, noop),
    ]
