# Generated by Django 2.2.6 on 2019-10-10 08:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [('bookrank', '0009_topic_typ_index'), ('hits', '0006_hittype_slug')]

    operations = [
        migrations.CreateModel(
            name='TopicHit',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('value', models.IntegerField(default=1)),
                (
                    'date',
                    models.DateField(
                        blank=True,
                        help_text='May be empty in cases where date is not known',
                        null=True,
                    ),
                ),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'source_work_hit',
                    models.ForeignKey(
                        help_text='May be null if the hit was direct and not via a Work',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='topic_hits',
                        to='hits.WorkHit',
                    ),
                ),
                (
                    'topic',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='bookrank.Topic'
                    ),
                ),
                (
                    'typ',
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to='hits.HitType'
                    ),
                ),
            ],
        )
    ]
