# Generated by Django 2.2.16 on 2020-11-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [('hits', '0008_createdupdatedmixin')]

    operations = [migrations.DeleteModel(name='TopicHit')]
